default:
    trainer: ppo
    batch_size: 256
    beta: 5.0e-3
    buffer_size: 1024
    epsilon: 0.2
    gamma: 0.999
    hidden_units: 256
    lambd: 0.9
    learning_rate: 1.0e-4
    max_steps: 5.0e8
    memory_size: 256
    normalize: true
    num_epoch: 1
    num_layers: 2
    time_horizon: 1024
    sequence_length: 128
    summary_freq: 1000
    use_recurrent: false
    use_curiosity: false
    curiosity_strength: 0.1
    curiosity_enc_size: 128
    augment_r: false
